### ISSUE TITLE
"The server requested authentication method unknown to the client" error

### ISSUE THREAD

**Issue by realgorgan** [EnergyCube/CoWFC#15]
Hi There!

I've been working on this as a school project for a LAN party and many other things!
I've been getting this error when trying to access the admin dashboard
(There was an error: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client)

I'd love to know what's going on and how to fix this, it's probably something really simple :|
Thanks!

Edit: This fixed the issue

open mysql in the terminal (just type mysql)
Use the following command
ALTER USER 'username here'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password here';
Leave the password empty if you don't want a password.
Use this user in your laravel env file for the MYSQL database.

**Comment by EnergyCube** [comment]
#16
