### ISSUE TITLE
Connect to VPS without domain

### ISSUE THREAD

**Issue by DadeKuma** [EnergyCube/CoWFC#17]
I'm trying to connect to the server with no luck.

I set up the server correctly and can view the dashboard and admin panel online. I have a VPS without a domain set. I'm using the Dolphin emulator, with my DNS set as the server IP.

I tried to connect using a Gecko cheat code to disable SSL that I found [here](https://mariokartwii.com/archive/index.php?thread-56.html), and I got the 20100 (unable to connect to the internet) error.  I tried again without, but I got the 23400 (too much traffic please contact Nintendo) error.  

What do you think am I missing?

**Comment by EnergyCube** [comment]
Hey I invite you to try this https://github.com/EnergyCube/cowfc_installer/issues/2#issuecomment-771182343 to patch the ISO with WIT

**Comment by DadeKuma** [comment]
Thank you, I will try with WIT. 

I'm also a bit confused about what is the purpose of the Fully Qualified Domain Name on server creation? Should I put "nintendowifi.net"? I'm not using any domain with my VPS.

**Comment by EnergyCube** [comment]
`Fully Qualified Domain Name` is your VPS domain name.
> I'm not using any domain with my VPS.

Oh sorry, I never tested without a domain name :( the DNS solution could work on a real Wii but on Dolphin I'm not sure sadly.

**Comment by DadeKuma** [comment]
I had to use a custom domain name, but it worked with WIT. Thank you!
