### ISSUE TITLE
Tables are not created

### ISSUE THREAD

**Issue by chauhoang99** [EnergyCube/CoWFC#3]
Hello kyle95wm,

Thanks for your sharing.

I tried to setup a server on AWS by following your bash file, and I got problem with the MySQL tables. The setup was successful, I can open and login the admin page, but the Whitelist page is not loaded properly. After debugging I figured out that the table whitelist is not created during setup.

Could you please instruct me what I should do?

Thank you

**Comment by EnergyCube** [comment]
Hey i'm kyl... EnergyCube :)

What system did you used on AWS ? Ubuntu or Debian ? And what was the version ?
Also, did you used the debian script or the ubuntu script ? Do you have a domain name and setup the CNAME ?

**Comment by chauhoang99** [comment]
Hi Kyl,

It's EC2 T2.micro - Ubuntu 16.04. I used the Ubuntu script. I don't have a domain name and did not setup the CNAME. I had to create the table allowed_games manually. Then I figured out that I did not config Apache properly, the auto config was interrupted due to failed installation of PHP7.1, this is another issue, seems like PHP7.1 is not available for Ubuntu 16 anymore. It is running now, I can access from my Wii :) Asking my friends to test too. Thank you :)

**Comment by EnergyCube** [comment]
Uhm, no when i write "Hey i'm kyl... EnergyCube :)" it was because i'm EnergyCube not kyle95wm xD
Anyway, it doesn't matter.

CooperAJ made a great tutorial on Youtube to install CoWFC on AWS : https://www.youtube.com/watch?v=b9EGrBL5gtE
Please note that without CNAME or a domain name you technically can't host a server on AWS.
If you want to create a compatible script with AWS do not hesitate to create a pull request.

If you have any other questions don't hesitate.

**Comment by cooperaj** [comment]
Nope, not me, but carry on ;)

**Comment by chauhoang99** [comment]
Opss sorry EnergyCube,

Oh I see, without a domain name https requests won't work. Yea that's why I cannot connect if I play from disk. I can disable the https on my usb loader and can connect, but will be better if it can handle https too. Let me clean up the file a bit then I will create new pr for AWS.

**Comment by chauhoang99** [comment]
Hi EnergyCube,

Please review my pr: https://github.com/EnergyCube/cowfc_installer/pull/7

**Comment by EnergyCube** [comment]
Closing issue.
If the problem happens again, do not hesitate to respond to the issue.

**Comment by jeffabner** [comment]
> table allowed_games

friend, I think I have the same problem, only the page http://192.168.33.128/?page=admin&section=dashboard loads, the others don't, I could share the sql to create all the tables that the server needs, here it is the 'users' table
