### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by 970319835** [EnergyCube/CoWFC#5]
I can't open the web page after installing Ubuntu 14.04 and 16.04. After I scan, port 80 is closed. However, if I use 20.4, the installation can succeed, but there was an error: sqlstate [HY000] [2054]....

**Comment by EnergyCube** [comment]
Any news ?

**Comment by EnergyCube** [comment]
No news since 1 month, closing the issue.
If you have any news or information please feel free to reopen the issue.
