### ISSUE TITLE
Connecting to the server.

### ISSUE THREAD

**Issue by Optllizer** [EnergyCube/CoWFC#6]
How exactly do you connect to the server? I patched my main.dol and staticr.rel with my domain/ip address + Anti freeze codes + no-SSL codes using wiimms tools. I tried just an IP but it didn't work. I tried making a domain and forwarding the IP to my server's IP, didn't work. I tried todo the dwc DNS setup and still did not work. the admin panel is up and functioning tho so I don't know what I am missing.

The game gives me 20100(Unable to connect to internet) for Domain set as my servers IP.
The game gives me 20101(Either WFC is experiencing high traffic or is down) for both my domain forwarded to my IP and the DNS setup.

Running Debian 9( I know you say 10 is required but the webpage is working) I tried Ubuntu 16.04 but the panel did not work because it doesn't want to install PHP7.1 for whatever reason. Not sure if Debian 9 would cause these issues.

If you have discord, could you please add me Optllizer#4569 I feel it will be easier to troubleshoot?

**Comment by EnergyCube** [comment]
Hi,

First of all, before trying to add extra geecko code inside main.dol or staticr.rel, try doing this to check that your game can connect to the server.
https://github.com/EnergyCube/cowfc_installer/issues/2#issuecomment-771182343

**Comment by Optllizer** [comment]
I will try that method. But just so you know ubuntu 16.04 does not work correctly because the Repo for php7.1 isn't supported anymore. Even the third-party repo doesn't support it anymore.

**Comment by EnergyCube** [comment]
Yeah I know but I didn't take the time to fix it actually, sorry, I'm pretty busy.
If someone managed to replace the repo with another version, I would update the installer.

**Comment by EnergyCube** [comment]
Any news ?

**Comment by Optllizer** [comment]
I haven't had time todo anything I am also busy with classes. I will mess around with it soon.

**Comment by EnergyCube** [comment]
No news since 2 month.
Reopen the issue if you have any news.
