### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by Wit-MKW** [EnergyCube/CoWFC#7]
Hello. How would I go about using an SSL certificate with this server? I've tried editing the Apache2 config files to that effect to no avail.

**Comment by EnergyCube** [comment]
Hi,

Are you using CoWFC for Wii or NDS games ?

**Comment by EnergyCube** [comment]
Any news ?

**Comment by EnergyCube** [comment]
No news since 1 month.
Reopen the issue if you have any news.
